target("RyuMath")
	set_group("Ryu/Core")
	set_kind("headeronly")
	add_includedirs(".", { public = true })
	add_includedirs("$(projectdir)/External", { public = true })
	add_headerfiles("**.h")
target_end()
