# Ryu Engine Configuration
[Paths]
# Project directory (relative to engine root)
ProjectDir = "Testbench"

# Game DLL file name (will be combined with current working directory)
GameDLLName = "RyuTestbench.dll"
