target("RyuInput")
	add_rules("IncludeConfigs", "CommonPackages")
	add_rules("RyuPlugin", { built_for = "Engine" })
	add_includedirs("..", { public = true })
	add_files("**.cpp")
	add_headerfiles("**.h")
target_end()