target("RyuProfiling")
	set_group("Ryu/Core")
	set_kind("headeronly")
	add_includedirs(".", { public = true })
	add_headerfiles("**.h")
	add_deps("RyuCommon", "TracyClient")
	add_rules("c++.unity_build")
target_end()
