target("RyuProfiling")
	set_group("Ryu/Core")
	set_kind("headeronly")
	add_includedirs(".", { public = true })
	add_headerfiles("**.h")
	add_deps("RyuCommon")
	add_rules("c++.unity_build")
	add_packages("tracy", { public = true })
	add_options("ryu-enable-tracy-profiling", { public = true })
target_end()
