option("ryu-log-trace-enabled")
	set_showmenu(true)
	set_default(true)
	set_category("root Ryu/Logging")
	set_description("Compile time switch to enable trace verbosity logs")
option_end()

option("ryu-log-debug-enabled")
	set_showmenu(true)
	set_default(true)
	set_category("root Ryu/Logging")
	set_description("Compile time switch to enable debug verbosity logs")
option_end()

option("ryu-log-info-enabled")
	set_showmenu(true)
	set_default(true)
	set_category("root Ryu/Logging")
	set_description("Compile time switch to enable info verbosity logs")
option_end()

option("ryu-log-warn-enabled")
	set_showmenu(true)
	set_default(true)
	set_category("root Ryu/Logging")
	set_description("Compile time switch to enable warn verbosity logs")
option_end()

option("ryu-assert-on-fail-hresult")
	set_showmenu(true)
	set_default(true)
	set_description("Assert on failure of HRESULT")
	set_category("root Ryu/Graphics")
option_end()

option("ryu-enable-tracy-profiling")
	set_showmenu(true)
	set_default(false)
	set_description("Enable profiling")
	set_category("root Ryu/Profiling")
	add_defines("RYU_PROFILING_ENABLED", "TRACY_ENABLE")
option_end()

option("ryu-rhi-dx11")
	set_showmenu(true)
	set_default(true)
	set_description("Enabled D3D11 graphics API")
	set_category("root Ryu/Graphics")
option_end()

option("ryu-rhi-dx12")
	set_showmenu(true)
	set_default(false)
	set_description("Enabled D3D12 graphics API")
	set_category("root Ryu/Graphics")
option_end()
