option("use-std-types-globally")
	set_showmenu(true)
	set_default(true)
	set_description("Bring Ryu::Common::StandardTypes to the global namespace")
	set_category("root Ryu")
option_end()

option("assert-on-fail-hresult")
	set_showmenu(true)
	set_default(false)
	set_description("Assert on failure of HRESULT")
	set_category("root Ryu/Graphics")
option_end()

option("ryu-enable-tracy-profiling")
	set_showmenu(true)
	set_default(false)
	set_description("Enable profiling")
	set_category("root Ryu/Profiling")
	add_defines("RYU_PROFILING_ENABLED", "TRACY_ENABLE")
option_end()
