target("SamplePlugin")
	set_group("Plugins")
	set_kind("shared")
	set_default(true)
	add_includedirs(".", { public = true })
	add_files("**.cpp")
	add_headerfiles("**.h")
	add_deps("RyuEngine")
	add_defines("RYU_PLUGIN_API_EXPORTS")
target_end()
