[Debugging]
PressEscapeToClose = true

[Log]
EnableLogToConsole = false
EnableLogToFile = true
ForceLogToOutput = true
LogFilePath = "Logs/LogTestbench.txt"

[Window]
WindowMinimumSize = [ 800, 600 ]
WindowPosition = [ -2147483648, -2147483648 ]
WindowSize = [ 1280, 720 ]
WindowTitle = "Ryu Testbench"
