target("RyuGraphics")
	set_kind("static")
	set_group("Ryu/Core")

	add_deps("RyuCommon")

	add_includedirs(".", { public = true })
	add_files("**.cpp", { unity_group = "IOC" })
	add_headerfiles("**.h")
	add_rules("c++.unity_build")
target_end()
target("RyuIOC")
	set_kind("static")
	set_group("Ryu/Core")
	add_deps("RyuUtils")
	add_includedirs(".", { public = true })
	add_files("**.cpp", { unity_group = "IOC" })
	add_headerfiles("**.h")
	add_rules("c++.unity_build")
target_end()
