# This file contains the engine configuration and is embedded into the binary

# A plugin definition contains the following
# -> Name: The name of the plugin
# -> LoadOrder: The order in which the plugin should be loaded (PreInit, PostInit, Default = PostInit)
# -> TickOrder: The order in which the plugin should be ticked (PreUpdate, PostUpdate, Default = PostUpdateick)
# -> RenderOrder: The order in which the plugin should be rendered (PreRender, PostRender, Default = PostRender)
# Setting TickOrder or RenderOrder to 'None' will disable ticking or rendering for that plugin


[[Plugins]]
Name = "RyuInput"
LoadOrder = "PostInit"
TickOrder = "None"
RenderOrder = "None"
