[Properties]
HasCloseButton = true
HasMaximizeButton = true
HasMinimizeButton = true
IsResizable = true
IsVisible = true
Title = "Testbench"
Position = [ -2147483648, -2147483648 ] # Centered

[Size]
MinimumSize = [ 800, 600 ]
Size = [ 1280, 720 ]
